-- ============================================================================
-- warehouse/lgpd.sql - governanca / LGPD na camada Gold (perfil full / defesa).
-- Mascara de PII (nome/cidade do cliente), tabela de auditoria de acesso e
-- exemplo de anonimizacao (direito ao esquecimento no relacional). O DELETE
-- fisico da telemetria vive no Delta (batch/spark/jobs/lgpd_delete.py). Camera
-- 360 + geolocalizacao sao dados sensiveis (plano secao 3.8).
-- Aplicar sob demanda: psql ... -f warehouse/lgpd.sql
-- ============================================================================
SET search_path TO dw_locadora;

-- --- View com PII mascarada (uso por perfis sem necessidade de identificar) --
CREATE OR REPLACE VIEW v_cliente_mascarado AS
SELECT
    sk_cliente,
    -- mantem a inicial + mascara o restante do nome
    CASE WHEN nome IS NULL THEN NULL
         ELSE LEFT(nome, 1) || REPEAT('*', GREATEST(LENGTH(nome) - 1, 0)) END AS nome_mascarado,
    -- cidade/UF preservadas para analise agregada (nao identificam sozinhas)
    cidade, estado, faixa_etaria
FROM Dim_Cliente;

-- --- Tabela de auditoria de acesso (audit log) ------------------------------
CREATE TABLE IF NOT EXISTS lgpd_audit_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ts          TIMESTAMPTZ NOT NULL DEFAULT now(),
    ator        VARCHAR(80) NOT NULL,
    operacao    VARCHAR(40) NOT NULL,        -- SELECT_PII | ANONIMIZAR | EXPORTAR
    alvo        VARCHAR(120),
    detalhe     TEXT
);

-- --- Anonimizacao de um cliente (direito ao esquecimento no relacional) ------
-- Uso: SELECT dw_locadora.anonimizar_cliente('CLI-003', 'operador.dpo');
CREATE OR REPLACE FUNCTION anonimizar_cliente(p_id_origem VARCHAR, p_ator VARCHAR)
RETURNS VOID LANGUAGE plpgsql AS $$
DECLARE v_sk INTEGER;
BEGIN
    SELECT sk_cliente INTO v_sk FROM Dim_Cliente WHERE id_cliente_origem = p_id_origem;
    IF v_sk IS NULL THEN RAISE NOTICE 'cliente % nao encontrado', p_id_origem; RETURN; END IF;

    UPDATE Dim_Cliente
       SET nome = 'ANONIMIZADO', cidade = NULL, id_cliente_origem = 'ANON-' || v_sk
     WHERE sk_cliente = v_sk;

    INSERT INTO lgpd_audit_log (ator, operacao, alvo, detalhe)
    VALUES (p_ator, 'ANONIMIZAR', p_id_origem, 'Direito ao esquecimento (LGPD art. 18)');
END; $$;

-- --- Retencao (exemplo): telemetria diaria com mais de 400 dias vira agregada -
-- (a serie fina no Cassandra usa TTL por familia de coluna; aqui, a Gold).
-- DELETE FROM Fato_Telemetria_Diaria
-- WHERE sk_tempo < TO_CHAR(CURRENT_DATE - 400, 'YYYYMMDD')::int;
